"""empty message

Revision ID: ab47c20d79b2
Revises: 
Create Date: 2025-06-05 23:42:18.592138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab47c20d79b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('menu', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('datetime', sa.String(length=50), nullable=False))
        batch_op.drop_column('message')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('datetime')
        batch_op.drop_column('menu')
        batch_op.drop_column('status')
        batch_op.drop_column('city')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
